// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvQmacyzKXTiXvHgyvbC5_TdRQj0b3xAE',
    appId: '1:770773510083:web:2efd7384964b76934c7f76',
    messagingSenderId: '770773510083',
    projectId: 'push-notification-14f95',
    authDomain: 'push-notification-14f95.firebaseapp.com',
    storageBucket: 'push-notification-14f95.appspot.com',
    measurementId: 'G-MEZ0NSPSH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACgo9xDuP7DVzi7KNDePxDcfYRY1z-YD0',
    appId: '1:770773510083:android:a2f37a5684130e134c7f76',
    messagingSenderId: '770773510083',
    projectId: 'push-notification-14f95',
    storageBucket: 'push-notification-14f95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5JX08m3g9B5hvDLh_k2sCHOVXNzC1VuQ',
    appId: '1:770773510083:ios:9125d6618b75aba74c7f76',
    messagingSenderId: '770773510083',
    projectId: 'push-notification-14f95',
    storageBucket: 'push-notification-14f95.appspot.com',
    iosClientId: '770773510083-4qdbv8kvjj0untoijuli5mb7iha7jhsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5JX08m3g9B5hvDLh_k2sCHOVXNzC1VuQ',
    appId: '1:770773510083:ios:9125d6618b75aba74c7f76',
    messagingSenderId: '770773510083',
    projectId: 'push-notification-14f95',
    storageBucket: 'push-notification-14f95.appspot.com',
    iosClientId: '770773510083-4qdbv8kvjj0untoijuli5mb7iha7jhsv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushNotification',
  );
}
